name: eopy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 2.7
  #
  # dependencies
  #
  - numpy=1.16.*
  - scipy=1.2.*
  - matplotlib=2.2.*
  - netCDF4=1.5.*
  - geopy=1.18.*
  - shapely=1.6.*
  - Pillow=5.3.*
  - xarray=0.11.3